openapi: 3.0.0
info:
  title: DEA Field Manager API
  version: 1.0.0
  description: API para gerenciamento de projetos e instalações de campo

servers:
  - url: https://[seu-projeto].supabase.co/functions/v1/public-api
    description: Produção

security:
  - BearerAuth: []

paths:
  /docs:
    get:
      summary: Documentação da API
      responses:
        200:
          description: Documentação em JSON
  
  /projects:
    get:
      summary: Listar projetos do usuário
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [planning, in-progress, completed, on-hold, cancelled]
      responses:
        200:
          description: Lista de projetos
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Project'
        401:
          $ref: '#/components/responses/Unauthorized'
    
    post:
      summary: Criar novo projeto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, client, city]
              properties:
                name:
                  type: string
                  example: "Projeto Shopping ABC"
                client:
                  type: string
                  example: "Shopping ABC LTDA"
                city:
                  type: string
                  example: "São Paulo"
                code:
                  type: string
                  example: "SHOP-001"
                status:
                  type: string
                  enum: [planning, in-progress]
      responses:
        201:
          description: Projeto criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

  /projects/{id}:
    get:
      summary: Obter projeto específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Dados do projeto
        404:
          description: Projeto não encontrado

  /projects/{id}/installations:
    get:
      summary: Listar instalações do projeto
      responses:
        200:
          description: Lista de instalações

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: API Key gerada no sistema
  
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        client:
          type: string
        city:
          type: string
        code:
          type: string
        status:
          type: string
          enum: [planning, in-progress, completed, on-hold, cancelled]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
    Installation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        project_id:
          type: string
          format: uuid
        codigo:
          type: integer
        descricao:
          type: string
        tipologia:
          type: string
        pavimento:
          type: string
        quantidade:
          type: integer
        installed:
          type: boolean
  
  responses:
    Unauthorized:
      description: API Key inválida ou ausente
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid or missing API key"
